name: Update World Cup Table

on:
  schedule:
    - cron: '0 */6 * * *' # รันอัตโนมัติทุกวันเวลา 07:00 น. เวลาไทย
  workflow_dispatch:   # เปิดสวิตช์ให้กดรันเองด้วยมือได้

permissions:
  contents: write
  pages: write        # <--- เพิ่มสิทธิ์ในการเขียนหน้าเว็บ Pages
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run build script
      run: python scripts/build.py

    - name: Commit and Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update table data" && git push)

    - name: Upload artifact for Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs' # ดึงเฉพาะไฟล์หน้าเว็บในโฟลเดอร์ docs ไปแสดงผล

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      
